### ISSUE TITLE
Use Github API instead of Puppeteer

### ISSUE THREAD

**Issue by ThallesP** [caioagiani/github-typos-scan#10]
We can use the Github API to do the search instead of launching an entire browser for it
Also, we can offer the option to the user to select if he wants to provide an API key which will be fast because of the rate limit.
See more here: https://docs.github.com/en/rest/reference/search#search-code
I already did some tests and works fine, I can open a pull request now to work on this if there isn't any problem for you.

#11

**Comment by caioagiani** [comment]
The initial idea of the project would be to do searches without authentication, however, of course, it would be much better in all benchmarks to use api key and endpoint route.
It would be amazing to have a PR with this functionality!!!

**Comment by ThallesP** [comment]
The Github API also supports unauthorized requests, about 10 requests per minute, so we wouldn't lose anything, I'll open a pull request soon!
